version: "3.8"
services:
  python-llm-service:
    build: ./python-llm-service
    container_name: python-llm-service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5001:5001"
    image: mirror.gcr.io/library/python:3.9-slim

  node-llm-service:
    build: ./node-llm-service
    container_name: node-llm-service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWITTER_RAPIDAPI_KEY=${TWITTER_RAPIDAPI_KEY}
    ports:
      - "5002:5002"
    image: mirror.gcr.io/library/node:18-alpine
    dns:
      - 8.8.8.8
      - 8.8.4.4

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    depends_on:
      - python-llm-service
      - node-llm-service
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - orchestrator
    ports:
      - "3000:80"